### ISSUE TITLE
about the word2vectors

### ISSUE THREAD

**Issue by Tanwey** [ikuinen/CMIN#1]
Hi,

I wana to know about how you process the word vectors dataset?

Looking forward to your reply

**Comment by ikuinen** [comment]
As for query in the dataset, we simply remove the stop words of the sentence and use the pretrained glove word vectors as the initial feature representation.
The word vectors can be turned into binary format for fast IO.
Hope this may help you.

**Comment by Tanwey** [comment]
Hi,

Thank you so much!

But I still have a problem.Could you tell me which pretrained golve word vectors dataset you used?

Looking forward to ypur reply

**Comment by ikuinen** [comment]
> Hi,
> 
> Thank you so much!
> 
> But I still have a problem.Could you tell me which pretrained golve word vectors dataset you used?
> 
> Looking forward to ypur reply

You can download it [here](http://nlp.stanford.edu/data/glove.840B.300d.zip).
