### ISSUE TITLE
Loading Pretrained Model

### ISSUE THREAD

**Issue by AmeenAli** [ikuinen/CMIN#10]
Where can i Find in code the Pretrained Model loading?
Because I can't see that this is implemented.
Best

**Comment by ikuinen** [comment]
Since the training can be fast, you can easily achieve the results.
You can load your trained model as follows:
```
self.model.load_state_dict(torch.load(model_path))
```

> Where can i Find in code the Pretrained Model loading?
> Because I can't see that this is implemented.
> Best
