### ISSUE TITLE
How to get the video C3D features' vectors datasets

### ISSUE THREAD

**Issue by wangsu1999** [ikuinen/CMIN#2]
Hello,

Thanks for your sharing.
But I have something trouble to get the datasets of the video C3D features'  vectors ,which is fit for this codes.Could you tell me about the steps to get the C3D features or share your C3D features?

Best

**Comment by ikuinen** [comment]
> Hello,
> 
> Thanks for your sharing.
> But I have something trouble to get the datasets of the video C3D features' vectors ,which is fit for this codes.Could you tell me about the steps to get the C3D features or share your C3D features?
> 
> Best

The C3D features of ActivityCaptions can be downloaded [here](http://activity-net.org/challenges/2016/download.html), and the way of feature extraction is presented here:
> The publicly available pre-trained C3D model which has a temporal resolution of 16 frames was used to extract frame based features. This network was not fine-tuned on our data. We reduce the dimensionality of the activations from the second fully-connected layer (fc7) of our visual encoder from 4096 to 500 dimensions using PCA. The C3D features were extracted every 8 frames.

This is exactly the way we apply to extract visual features  of videos  in TACoS.
Hope this may help you!

**Comment by wangsu1999** [comment]
Thank you.
It is very helpful for me.
