### ISSUE TITLE
about the glove_model.bin 

### ISSUE THREAD

**Issue by zqlearning** [ikuinen/CMIN#5]
Hi,
Thanks for your sharing.
I don't know where to find it,
looking forward to your reply

**Comment by ikuinen** [comment]
The word2vec model "glove_model.txt" can be converted into binary format for faster IO using
gensim.
```
from gensim.models import KeyedVectors
KeyedVectors.save_word2vec_format(..., binary=True)
```

**Comment by yxinli92** [comment]
Hi @ikuinen could you help point out where can I find this "glove_model.txt", thanks!

**Comment by wangwen39** [comment]
You can convert [glove.840B.300d.txt(https://nlp.stanford.edu/projects/glove/) to glove.840B.300d.bin.
