### ISSUE TITLE
about the R@5

### ISSUE THREAD

**Issue by Tanwey** [ikuinen/CMIN#6]
Hello,

I don't know hoew to get the R@5.Could you tell me the changes of the code you share now?

Looking forward to your reply.

**Comment by ikuinen** [comment]
Please refer to this [response](https://github.com/ikuinen/CMIN_moment_retrieval/issues/11#issuecomment-633960062).

> Hello,
> 
> I don't know hoew to get the [R@5.Could](mailto:R@5.Could) you tell me the changes of the code you share now?
> 
> Looking forward to your reply.
