### ISSUE TITLE
Request for Tacos feature

### ISSUE THREAD

**Issue by yangwf1** [ikuinen/CMIN#7]
Thanks for your code, is it convenient for you to provide the processed feature for Tacos dataset?

**Comment by ikuinen** [comment]
> Thanks for your code, is it convenient for you to provide the processed feature for Tacos dataset?

@yangwf1 Please refer to this response [here](https://github.com/ikuinen/CMIN_moment_retrieval/issues/4#issuecomment-592094714), or you can download C3D features [here](https://drive.google.com/drive/folders/1D3nav3TKZmYNHvSLBgDt1vpBUXoV2MRv).
