### ISSUE TITLE
about the train_data_gcn.json

### ISSUE THREAD

**Issue by xixiareone** [ikuinen/CMIN#9]
Hi! 
How to prepare train_data gcn.json, can you share the code for preparing train _data gcn.json?

**Comment by ikuinen** [comment]
@xixiareone You can use the _nltk_ to build the semantic dependencies. Note that you should start the StanfordCoreNLP server at port 9000. (refer to [here](https://github.com/stanfordnlp/CoreNLP/issues/483#issuecomment-339870707))
```
from nltk.parse.corenlp import CoreNLPDependencyParser
dep_parser = CoreNLPDependencyParser(url='http://localhost:9000')
parse, = dep_parser.raw_parse(sentence)
```

**Comment by xixiareone** [comment]
hi，thank you very much!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LinZhijie"<notifications@github.com&gt;; 
发送时间: 2020年4月9日(星期四) 下午5:35
收件人: "ikuinen/CMIN_moment_retrieval"<CMIN_moment_retrieval@noreply.github.com&gt;; 
抄送: "Gin"<xixiareone@foxmail.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ikuinen/CMIN_moment_retrieval] about the train_data_gcn.json (#9)





 
@xixiareone您可以使用nltk构建语义依赖关系。请注意，您应该在端口9000上启动StanfordCoreNLP服务器。（请参阅此处）
 from nltk.parse.corenlp import CoreNLPDependencyParser dep_parser = CoreNLPDependencyParser(url='http://localhost:9000') parse, = dep_parser.raw_parse(sentence)  
- 
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
